/**
 * kdramascraperapi – Drama Scraper Config
 * Generated by @zjkm666/scraperapi (template: video, fixed for kisskh.do)
 *
 * kisskh.do exposes a direct JSON API (better than HTML scraping):
 *   /api/DramaList/Search?q=&type= | /api/DramaList/List | /api/DramaList/MostSearch
 *   /api/DramaList/Drama/:id | /api/DramaList/Episode/:epsId.png | /api/Sub/:epsId
 * Those are wired below as kind:'api' (JSON proxy). HTML scrape endpoints
 * are kept as fallback.
 * Stream/Sub calls need a short-lived `kkey` (pass ?kkey= or set
 * KISSKH_STREAM_KEY / KISSKH_SUB_KEY env). HLS .m3u8 URLs are returned as
 * data – play them client-side, don't proxy video bytes through this server.
 */

const DRAMA_CARD = '.neo-directory-card, .drama-card, .movie-card, .video-card, .video-item';
const DRAMA_FIELDS = {
  title: '.neo-directory-title, .title, h3, .video-title, .drama-title, [class*="title"]',
  link: 'a@href',
  thumbnail: '.neo-directory-poster img@src | img@src | img@data-src | img@data-lazy-src',
  type: '.neo-directory-type, .type, [class*="type"]',
  status: '.neo-directory-status, .status, [class*="status"]',
  year: '.neo-directory-year, .year, [class*="year"], time',
  score: '.neo-directory-score, .score, .rating, [class*="rating"], [class*="score"]',
};

module.exports = {
  name: 'kdramascraperapi',
  sourceUrl: 'https://kisskh.do/',

  cache: {
    enabled: true,
    ttl: 300,
    checkperiod: 60,
  },

  renderJs: true,

  fetchOpts: {},

  endpoints: [
    // ── Direct JSON API (preferred) ──────────────────────────────────
    {
      method: 'GET',
      path: '/api/search',
      kind: 'api',
      cache: { ttl: 120 },
      buildUrl: (baseUrl, req) => {
        const q = req.query?.q || req.body?.q || req.query?.query || '';
        if (!q) throw new Error('Missing required query param: q');
        const type = req.query?.type ?? 0;
        return `${baseUrl}/api/DramaList/Search?q=${encodeURIComponent(q)}&type=${encodeURIComponent(String(type))}`;
      },
      description: 'Search dramas (JSON) – GET /api/search?q=marry%20my%20husband&type=0',
    },
    {
      method: 'GET',
      path: '/api/list',
      kind: 'api',
      cache: { ttl: 300 },
      buildUrl: (baseUrl, req) => {
        const p = new URLSearchParams();
        p.set('page', String(req.query?.page ?? 1));
        if (req.query?.type != null) p.set('type', String(req.query.type));
        if (req.query?.sub != null) p.set('sub', String(req.query.sub));
        if (req.query?.country != null) p.set('country', String(req.query.country));
        if (req.query?.status != null) p.set('status', String(req.query.status));
        if (req.query?.order != null) p.set('order', String(req.query.order));
        return `${baseUrl}/api/DramaList/List?${p.toString()}`;
      },
      description: 'Paginated drama list (JSON) – GET /api/list?page=1&type=1&order=2',
    },
    {
      method: 'GET',
      path: '/api/most-search',
      kind: 'api',
      cache: { ttl: 600 },
      buildUrl: (baseUrl, req) => {
        const ispc = req.query?.ispc ?? 'true';
        return `${baseUrl}/api/DramaList/MostSearch?ispc=${encodeURIComponent(String(ispc))}`;
      },
      description: 'Most-searched keywords (JSON) – GET /api/most-search?ispc=true',
    },
    {
      method: 'GET',
      path: '/api/drama',
      kind: 'api',
      cache: { ttl: 600 },
      buildUrl: (baseUrl, req) => {
        const id = req.query?.id || req.body?.id || '';
        if (!id) throw new Error('Missing required query param: id');
        const isq = req.query?.isq ?? 'false';
        return `${baseUrl}/api/DramaList/Drama/${encodeURIComponent(String(id))}?isq=${encodeURIComponent(String(isq))}`;
      },
      description: 'Drama detail + episodes (JSON) – GET /api/drama?id=8409&isq=false',
    },
    {
      method: 'GET',
      path: '/api/episode',
      kind: 'api',
      resolveEpisode: true,
      cache: { ttl: 60 },
      buildUrl: (baseUrl, req) => {
        const epsId = req.query?.epsId || req.query?.ep || '';
        if (!epsId) throw new Error('Missing required query param: epsId');
        const kkey = req.query?.kkey || process.env.KISSKH_STREAM_KEY || '';
        if (!kkey) {
          const e = new Error('kkey required: mint one via GET /api/kkey?dramaId=&epsId= then retry as /api/episode?epsId=&kkey=');
          e.status = 400;
          throw e;
        }
        const p = new URLSearchParams({ err: 'false', ts: '', time: '' });
        p.set('kkey', String(kkey));
        return `${baseUrl}/api/DramaList/Episode/${encodeURIComponent(String(epsId))}.png?${p.toString()}`;
      },
      description: 'Episode stream URLs {Video, ThirdParty m3u8} – GET /api/episode?epsId=144044&kkey=... or ?dramaId=8409&ep=1&kkey=...',
    },
    {
      method: 'GET',
      path: '/api/sub',
      kind: 'api',
      resolveEpisode: true,
      cache: { ttl: 60 },
      buildUrl: (baseUrl, req) => {
        const epsId = req.query?.epsId || req.query?.ep || '';
        if (!epsId) throw new Error('Missing required query param: epsId');
        const kkey = req.query?.kkey || process.env.KISSKH_SUB_KEY || '';
        if (!kkey) {
          const e = new Error('kkey required: mint one via GET /api/kkey?dramaId=&epsId= then retry as /api/sub?epsId=&kkey=');
          e.status = 400;
          throw e;
        }
        const p = new URLSearchParams({ kkey: String(kkey) });
        return `${baseUrl}/api/Sub/${encodeURIComponent(String(epsId))}?${p.toString()}`;
      },
      description: 'Episode subtitles, English-only by default [{src,label}] – GET /api/sub?epsId=144044&kkey=... or ?dramaId=8409&ep=1&kkey=...[&lang=id|all]',
      map: (raw, req) => {
        const { filterSubtitles } = require('./scraper');
        return filterSubtitles(raw, req.query?.lang || req.body?.lang || 'en');
      },
    },
    // ── HTML scrape (fallback) ───────────────────────────────────────
    {
      method: 'GET',
      path: '/videos',
      selector: `${DRAMA_CARD}, article`,
      fields: DRAMA_FIELDS,
      limit: 30,
      fetchOpts: { waitForSelector: '.neo-directory-card, .drama-card, .video-card, article' },
      cache: { ttl: 300 },
      description: 'List dramas (alias, kept for compat – prefer /dramas)',
    },
    {
      method: 'GET',
      path: '/dramas',
      selector: `${DRAMA_CARD}, article`,
      fields: DRAMA_FIELDS,
      limit: 30,
      fetchOpts: { waitForSelector: '.neo-directory-card, .drama-card, .video-card, article' },
      cache: { ttl: 300 },
      description: 'List dramas from sourceUrl',
    },
    {
      method: 'GET',
      path: '/trending',
      selector: `${DRAMA_CARD}, article`,
      fields: DRAMA_FIELDS,
      limit: 30,
      fetchOpts: { waitForSelector: '.neo-directory-card, .drama-card, .video-card, article' },
      cache: { ttl: 300 },
      description: 'Trending/popular dramas',
    },
    {
      method: 'POST',
      path: '/search',
      selector: `${DRAMA_CARD}, article`,
      fields: DRAMA_FIELDS,
      limit: 30,
      fetchOpts: { waitForSelector: '.neo-directory-card, .drama-card, .video-card, article' },
      cache: { ttl: 120 },
      buildUrl: (baseUrl, req) => {
        const q = req.body?.query || req.body?.q || req.query?.q || '';
        if (!q) return baseUrl;
        // kisskh.do SPA search; WP clones use /?s= – override via SOURCE_URL + custom buildUrl if needed
        return `${baseUrl}/search?q=${encodeURIComponent(q)}`;
      },
      description: 'Search dramas – POST { query: "queen of tears" }',
    },
    {
      method: 'GET',
      path: '/video-detail',
      selector: 'body',
      single: true,
      fields: {
        title: 'h1, .video-title, .drama-title, .neo-directory-title',
        description: '.description, [class*="description"], .synopsis, [class*="synopsis"]',
        type: '.neo-directory-type, .type, [class*="type"]',
        status: '.neo-directory-status, .status, [class*="status"]',
        year: '.neo-directory-year, .year, .date, time',
        thumbnail: '.poster img@src | img@src',
        link: 'a@href',
      },
      buildUrl: (baseUrl, req) => {
        const id = req.query?.id || req.body?.id || '';
        if (!id) return baseUrl;
        // path-style id (slug). Full-URL ids are rejected by same-origin guard in server.js
        return `${baseUrl}/video/${encodeURIComponent(id)}`;
      },
      description: 'Drama detail (alias, kept for compat – prefer /drama-detail?id=slug)',
    },
    {
      method: 'GET',
      path: '/drama-detail',
      selector: 'body',
      single: true,
      fields: {
        title: 'h1, .video-title, .drama-title, .neo-directory-title',
        description: '.description, [class*="description"], .synopsis, [class*="synopsis"]',
        type: '.neo-directory-type, .type, [class*="type"]',
        status: '.neo-directory-status, .status, [class*="status"]',
        year: '.neo-directory-year, .year, .date, time',
        thumbnail: '.poster img@src | img@src',
        link: 'a@href',
      },
      buildUrl: (baseUrl, req) => {
        const id = req.query?.id || req.body?.id || '';
        if (!id) return baseUrl;
        return `${baseUrl}/video/${encodeURIComponent(id)}`;
      },
      description: 'Drama detail – GET /drama-detail?id=slug',
    },
  ],
};
