/**
 * kdramascraperapi – Express Scraper API
 * Generated by @zjkm666/scraperapi
 * Source: https://kisskh.do/
 *
 * Run:
 *   npm install
 *   npm run dev   # http://localhost:3000
 *
 * Customize:
 *   Edit api.config.js to add GET/POST endpoints.
 */
require('dotenv').config();
const express = require('express');
const cors = require('cors');
const NodeCache = require('node-cache');
const config = require('./api.config');
const { scrape } = require('./scraper');
const axios = require('axios');

const apiHttp = axios.create({
  timeout: 15000,
  maxRedirects: 5,
  headers: {
    'User-Agent':
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
    Accept: 'application/json, text/plain, */*',
  },
  validateStatus: () => true,
});

async function fetchJson(url, fetchOpts = {}) {
  const headers = { ...(fetchOpts.headers || {}) };
  const res = await apiHttp.get(url, {
    headers,
    timeout: fetchOpts.timeout || 15000,
    params: fetchOpts.params,
  });
  if (res.status >= 400) {
    const err = new Error(`HTTP ${res.status} for ${url}`);
    err.status = res.status;
    throw err;
  }
  return res.data;
}

const app = express();
const PORT = process.env.PORT || 3000;
// SOURCE_URL env override (documented in .env.example) takes precedence over config
const SOURCE_BASE = (process.env.SOURCE_URL || config.sourceUrl || '').replace(/\/$/, '');

// ── Middleware ───────────────────────────────────────────────────────
app.disable('x-powered-by');
const corsOrigin = process.env.CORS_ORIGIN;
app.use(
  cors(
    corsOrigin
      ? { origin: corsOrigin.split(',').map((s) => s.trim()).filter(Boolean) }
      : undefined
  )
);
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));

// minimal security headers (helmet-lite, no extra dep)
app.use((_req, res, next) => {
  res.set('X-Content-Type-Options', 'nosniff');
  res.set('X-Frame-Options', 'DENY');
  res.set('Referrer-Policy', 'no-referrer');
  res.set('Permissions-Policy', 'camera=(), microphone=(), geolocation=()');
  next();
});

// simple in-memory rate limiter: 120 req / 60s per IP (no extra dep)
const RATE_WINDOW_MS = Number(process.env.RATE_WINDOW_MS) || 60_000;
const RATE_MAX = Number(process.env.RATE_MAX) || 120;
const _hits = new Map();
setInterval(() => {
  const now = Date.now();
  for (const [ip, arr] of _hits) {
    const fresh = arr.filter((t) => now - t < RATE_WINDOW_MS);
    if (fresh.length) _hits.set(ip, fresh);
    else _hits.delete(ip);
  }
}, RATE_WINDOW_MS).unref?.();
app.use((req, res, next) => {
  const ip = req.ip || req.socket?.remoteAddress || 'unknown';
  const now = Date.now();
  const arr = (_hits.get(ip) || []).filter((t) => now - t < RATE_WINDOW_MS);
  arr.push(now);
  _hits.set(ip, arr);
  if (arr.length > RATE_MAX) {
    res.set('Retry-After', String(Math.ceil(RATE_WINDOW_MS / 1000)));
    return res.status(429).json({ success: false, error: 'Rate limit exceeded, slow down' });
  }
  next();
});

// simple logger
app.use((req, _res, next) => {
  console.log(`${new Date().toISOString()} ${req.method} ${req.path}`);
  next();
});

// ── Cache (optional) ─────────────────────────────────────────────────
const cacheEnabled = !!(config.cache && (config.cache.enabled !== false));
const cacheTtl = (config.cache && config.cache.ttl) || 300;
const cacheCheckperiod = (config.cache && config.cache.checkperiod) || 60;
const cache = cacheEnabled ? new NodeCache({ stdTTL: cacheTtl, checkperiod: cacheCheckperiod, useClones: false }) : null;

function cacheKeyFor(endpoint, url, req) {
  // include body/query for POST/GET variance
  const extra = endpoint.method?.toUpperCase() === 'POST' ? req.body : req.query;
  try {
    return `${endpoint.method}:${endpoint.path}:${url}::${JSON.stringify(extra || {})}`;
  } catch {
    return `${endpoint.method}:${endpoint.path}:${url}`;
  }
}

function isCacheEnabledFor(endpoint) {
  if (!cacheEnabled || !cache) return false;
  if (endpoint.cache === false) return false;
  if (endpoint.cache === true) return true;
  if (endpoint.cache && typeof endpoint.cache === 'object' && endpoint.cache.enabled === false) return false;
  return true;
}

function getTtlFor(endpoint) {
  if (endpoint.cache && typeof endpoint.cache === 'object' && endpoint.cache.ttl) return Number(endpoint.cache.ttl);
  return undefined;
}

// ── Helpers ──────────────────────────────────────────────────────────
function getBase() {
  return SOURCE_BASE;
}

function isAllowedTarget(targetUrl, ep) {
  try {
    const u = new URL(targetUrl);
    const baseOrigin = new URL(getBase()).origin;
    if (u.origin === baseOrigin) return true;
    // explicit per-endpoint allowlist for CDN / third-party JSON (e.g. HLS hosts)
    const allow = (ep && ep.allowHosts) || [];
    return allow.some((h) => {
      if (!h) return false;
      if (h.startsWith('*.')) return u.hostname.endsWith(h.slice(1));
      return u.hostname === h;
    });
  } catch {
    return false;
  }
}

function resolveUrl(endpoint, req) {
  const base = getBase();
  let out;
  if (typeof endpoint.buildUrl === 'function') {
    const built = endpoint.buildUrl(base, req);
    if (typeof built !== 'string' || !built.trim()) throw new Error('buildUrl must return a string URL');
    out = built.trim();
  } else if (typeof endpoint.buildUrl === 'string') {
    // string template with :param placeholders, e.g. "/product/:id"
    let url = endpoint.buildUrl;
    // replace :param from body/query/params
    const params = { ...(req.params || {}), ...(req.query || {}), ...(req.body || {}) };
    for (const [k, v] of Object.entries(params)) {
      url = url.replaceAll(`:${k}`, encodeURIComponent(String(v)));
    }
    // reject unfilled placeholders to avoid malformed / injectable URLs
    if (/\/:[a-zA-Z0-9_]+/.test(url)) throw new Error('Missing required URL parameter');
    out = url.startsWith('/') ? base + url : url;
  } else if (endpoint.url) {
    // deprecated alias for buildUrl string
    out = endpoint.url.startsWith('http') ? endpoint.url : base + endpoint.url;
  } else {
    out = base + (endpoint.pathSuffix || '');
  }
  // SSRF guard: only allow same-origin targets as sourceUrl (+ ep.allowHosts)
  if (!isAllowedTarget(out, endpoint)) throw new Error('Resolved URL is not allowed (must stay on source origin)');
  return out;
}

function mergeFetchOpts(ep) {
  const merged = { ...(config.fetchOpts || {}), ...(ep.fetchOpts || {}) };
  const headers = {
    ...((config.fetchOpts && config.fetchOpts.headers) || {}),
    ...((ep.fetchOpts && ep.fetchOpts.headers) || {}),
    ...(ep.headers || {}),
  };
  if (Object.keys(headers).length) merged.headers = headers;
  else delete merged.headers;
  return merged;
}

function validateConfig() {
  if (!getBase() || !/^https?:\/\//.test(getBase())) {
    throw new Error('sourceUrl must be a valid http(s) URL (api.config.js or SOURCE_URL env)');
  }
  if (!Array.isArray(config.endpoints) || config.endpoints.length === 0) {
    console.warn('⚠ api.config.js: no endpoints defined. Add entries to config.endpoints.');
  }
}

// ── Auto-register endpoints from config ──────────────────────────────
function registerEndpoints() {
  for (const ep of config.endpoints) {
    const method = (ep.method || 'GET').toLowerCase();
    if (!['get', 'post'].includes(method)) {
      console.warn(`Skipping endpoint with unsupported method: ${ep.method} ${ep.path}`);
      continue;
    }

    app[method](ep.path, async (req, res) => {
      const start = Date.now();
      let targetUrl;
      try {
        targetUrl = resolveUrl(ep, req);
      } catch (e) {
        return res.status(400).json({ success: false, error: e.message });
      }

      // per-endpoint renderJs override (defaults to global or false)
      const renderJs = ep.renderJs != null ? !!ep.renderJs : !!config.renderJs;
      const useCache = isCacheEnabledFor(ep);
      const cacheKey = useCache ? cacheKeyFor(ep, targetUrl, req) : null;

      if (useCache) {
        const hit = cache.get(cacheKey);
        if (hit) {
          res.set('X-Cache', 'HIT');
          return res.json({ success: true, cached: true, source: targetUrl, data: hit, tookMs: Date.now() - start });
        }
      }

      try {
        const isApi = ep.kind === 'api' || ep.api === true;
        let data;
        if (isApi) {
          const opts = mergeFetchOpts(ep);
          data = await fetchJson(targetUrl, {
            ...opts,
            headers: { Referer: `${getBase()}/`, Origin: getBase(), ...(opts.headers || {}) },
          });
        } else {
          data = await scrape({
            url: targetUrl,
            selector: ep.selector,
            fields: ep.fields || {},
            renderJs,
            fetchOpts: mergeFetchOpts(ep),
            single: !!ep.single,
            limit: ep.limit,
          });
        }

        if (useCache) {
          const ttl = getTtlFor(ep);
          if (ttl) cache.set(cacheKey, data, ttl);
          else cache.set(cacheKey, data);
          res.set('X-Cache', 'MISS');
        }

        res.json({
          success: true,
          cached: false,
          source: targetUrl,
          count: Array.isArray(data) ? data.length : data ? 1 : 0,
          data,
          tookMs: Date.now() - start,
        });
      } catch (err) {
        console.error(`[${ep.method} ${ep.path}] scrape failed:`, err.message);
        const status = err.status && err.status < 500 ? err.status : 502;
        res.status(status).json({
          success: false,
          error: 'Scrape failed',
          details: err.message,
          source: targetUrl,
        });
      }
    });

    const tag = ep.kind === 'api' || ep.api === true ? '[API]' : `selector "${ep.selector}"`;
    console.log(`  ↳ ${method.toUpperCase().padEnd(4)} ${ep.path}  →  ${tag}${ep.renderJs ? ' [JS]' : ''}`);
  }
}

// ── Health / meta ────────────────────────────────────────────────────
app.get('/', (_req, res) => {
  res.json({
    name: config.name,
    sourceUrl: getBase(),
    endpoints: config.endpoints.map((e) => ({
      method: e.method,
      path: e.path,
      kind: e.kind === 'api' || e.api === true ? 'api' : 'scrape',
      selector: e.selector,
      description: e.description || '',
    })),
    cache: cacheEnabled ? { enabled: true, ttl: cacheTtl, keys: cache.keys().length } : { enabled: false },
    docs: 'Edit api.config.js to customize GET/POST endpoints. Restart server after changes.',
  });
});

app.get('/health', (_req, res) => res.json({ status: 'ok', uptime: process.uptime() }));

app.get('/cache/stats', (_req, res) => {
  if (!cache) return res.json({ enabled: false });
  res.json({ enabled: true, ...cache.getStats(), keys: cache.keys().length });
});

app.delete('/cache', (req, res) => {
  if (!cache) return res.json({ enabled: false, message: 'Cache disabled' });
  // Optional protection: set CACHE_CLEAR_TOKEN env to require token
  const required = process.env.CACHE_CLEAR_TOKEN;
  if (required) {
    const got = req.headers['x-cache-token'] || req.query.token;
    if (got !== required) return res.status(401).json({ success: false, error: 'Unauthorized' });
  }
  cache.flushAll();
  res.json({ success: true, message: 'Cache cleared' });
});

// ── Boot ─────────────────────────────────────────────────────────────
validateConfig();
registerEndpoints();

// 404 – must be after registerEndpoints
app.use((req, res) => {
  res.status(404).json({
    success: false,
    error: 'Not found',
    available: config.endpoints.map((e) => `${e.method} ${e.path}`).concat(['GET /', 'GET /health']),
  });
});

if (require.main === module) {
  const server = app.listen(PORT, () => {
    console.log(`\n  🚀 kdramascraperapi running at http://localhost:${PORT}`);
    console.log(`     Source: ${getBase()}`);
    console.log(`     Cache : ${cacheEnabled ? `enabled (TTL ${cacheTtl}s)` : 'disabled'}`);
    console.log(`     Try   : curl http://localhost:${PORT}${config.endpoints[0]?.path || '/products'}\n`);
  });
  const shutdown = () => {
    server.close(() => {
      try {
        const { closeBrowser } = require('./scraper');
        if (typeof closeBrowser === 'function') closeBrowser().finally(() => process.exit(0));
        else process.exit(0);
      } catch {
        process.exit(0);
      }
    });
    setTimeout(() => process.exit(0), 5000).unref?.();
  };
  process.once('SIGINT', shutdown);
  process.once('SIGTERM', shutdown);
}

module.exports = app;
